name: app_prueba
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  lottie: ^2.4.0
  firebase_core: ^4.1.1
  firebase_auth: ^6.1.0
  cloud_firestore: ^6.0.2
  google_sign_in: ^5.1.0
  google_maps_flutter: ^2.13.1
  geolocator: ^14.0.2
  shared_preferences: ^2.2.3
  
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/conecta.png
    - assets/images/obstaculo.png
    - assets/images/fondo_conecta.png
    - assets/images/fondo_deteccion.png
    - assets/images/fondo_inicio.png
    - assets/images/fondo_registro.png
    - assets/images/fondo_registro2.png
    - assets/images/fondo_registroyinicio.png
    - assets/images/fondo_sos.png
    - assets/images/imagen_inicio.png
    - assets/images/recuperar_contrasena.png
    - assets/images/registroyinicio.png
    - assets/images/sos.png
    - assets/images/apple_logo.png
    - assets/images/google_logo.png
    - assets/images/cambiar_contraseÃ±a.png
    - assets/images/editar_cuenta.png
    - assets/images/cuenta.png
    - assets/images/configuracion.png
    - assets/images/bluetooth.png
    - assets/images/tutor_fondo1.png
    - assets/images/tutor_fondo2.png
    - assets/images/tutor_fondo3.png
    - assets/images/tutor1.png
    - assets/images/tutor2.png
    - assets/images/tutor3.png
    


